language: python
python:
- '2.7'
install:
- pip install -e .
- pip install coveralls
- pip install sure
- pip install py-inspector
script:
- rm -rf .coverage
- make test
after_success:
- coveralls
deploy:
  provider: pypi
  user: lojaintegrada
  password:
    secure:
  on:
    tags: true
    repo: lojaintegrada/LI-Pagador-Deposito
    all_branches: true
notifications:
  email:
    recipients:
    - contato@awsli.com.br
    - marcio.duarte@lojaintegrada.com.br
